- name: Disable apparmor
  # otherwise there is a known issue that prevents a container from being stopped with SIGTERM/SIGKILL
  # https://www.reddit.com/r/Ubuntu/comments/1d6b4aa/ubuntu_2404_lts_server_podman_cant_stop_or_remove/
  ansible.builtin.systemd_service:
    name: apparmor
    state: stopped
    enabled: false

- name: Install podman
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: true

- name: Pull podman xen-orchestra image
  containers.podman.podman_image:
    name: docker.io/ronivay/xen-orchestra

- name: Create xen-orchestra volume xo-server
  ansible.builtin.file:
    path: /opt/xen-orchestra/containers/xo-server
    state: directory
    mode: "0755"

- name: Create xen-orchestra volume redis
  ansible.builtin.file:
    path: /opt/xen-orchestra/containers/redis
    state: directory
    mode: "0755"

- name: Create xen-orchestra certs directory
  ansible.builtin.file:
    path: /opt/xen-orchestra/ssl
    state: directory
    mode: "0755"

- name: Create xen-orchestra container and systemd service file
  containers.podman.podman_container:
    name: xen-orchestra
    image: docker.io/ronivay/xen-orchestra
    state: present
    recreate: true
    ports:
      - "8080:80"
    volumes:
      - "/opt/xen-orchestra/containers/xo-server:/var/lib/xo-server"
      - "/opt/xen-orchestra/containers/redis:/var/lib/redis"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      stop_timeout: 120
      names: true

- name: Start xen-orchestra service on boot
  ansible.builtin.systemd_service:
    name: container-xen-orchestra
    enabled: true

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Copy nginx configuration
  ansible.builtin.copy:
    src: files/nginx/xen-orchestra.conf
    dest: /etc/nginx/conf.d/xen-orchestra.conf
    mode: "0755"

- name: Start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    daemon_reload: true
